type User {
    _id: ID!
    username: String!
    email: String!
    password: String!
}

type Article {
    _id: ID!
    title: String!
    content: String!
}

type Query {
    me: User
    serverTime: String
}
type Mutation {
    publishArticle(title: String!, content: String!): Article!
}