@url = http://localhost:3000/graphql
POST {{url}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
# 这个请求总是返回数字 6

{
    numberSix
}

###
POST {{url}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
# 这个请求总是返回数字 7

{
    numberSeven
}
###
POST {{url}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
# 根据 id 查找 user

{
    libraries{
        branch
        books {
            # 需要子字段
            author{
                name
            }
        }
    }
}














