
# https://www.jianshu.com/p/628953ba54f4?utm_campaign=maleskine&utm_content=note&utm_medium=seo_notes&utm_source=recommendation
### 自定义指令测试1
POST http://localhost:3000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL

{
     hello 
}
### 自定义指令测试2
POST http://localhost:3000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL

{
    hello2
}
### 自定义指令测试3
POST http://localhost:3000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL

{
  today
}